name: Cargo Check/Tests

on:
  - push

jobs:
  test:
    strategy:
      matrix:
        toolchain: [nightly]
        target: 
          - os: ubuntu-latest
            triple: [i686-unknown-linux-gnu, x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl]
          
          - os: windows-latest
            triple: [i686-pc-windows-gnu, i686-pc-windows-msvc, x86_64-pc-windows-gnu, x86_64-pc-windows-msvc]
          
          - os: macos-latest
            triple: [x86_64-apple-darwin]

    runs-on: ${{ matrix.target.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      
      - name: Cargo Check
        run: cargo check --target ${{ matrix.target }}
      
      - name: Cargo tests
        run: cargo test --target ${{ matrix.target }}
