name: Cargo Check/Tests

on:
  - push

jobs:
  test:
    strategy:
      matrix:
        toolchain: [nightly]
        target:
          - os: windows-latest
            triple: i686-pc-windows-msvc
          - os: windows-latest
            triple: x86_64-pc-windows-msvc
          - os: windows-latest
            triple: i686-pc-windows-gnu
          - os: windows-latest
            triple: x86_64-pc-windows-gnu
          
          - os: ubuntu-latest
            triple: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            triple: x86_64-unknown-linux-musl
          - os: ubuntu-latest
            triple: i686-unknown-linux-gnu
          
          - os: macos-latest
            triple: i686-apple-darwin
          - os: macos-latest
            triple: x86_64-apple-darwin

    runs-on: ${{ matrix.target.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      
      - name: Cargo Check
        run: cargo check --target ${{ matrix.target.triple }}
      
      - name: Cargo tests
        run: cargo test --target ${{ matrix.target.triple }}
